### ISSUE TITLE
error to run "python collect-fingerprints-of-songs.py"

### ISSUE THREAD

**Issue by hedo95** [itspoma/audio-fingerprint-identifying-python#17]
It shows me the next error:

MacBook-Pro-de-Jesus:audio-fingerprint-identifying-python jesushedo$ python collect-fingerprints-of-songs.py
sqlite - connection opened
Traceback (most recent call last):
  File "collect-fingerprints-of-songs.py", line 24, in <module>
    song = db.get_song_by_filehash(audio['file_hash'])
  File "/Users/jesushedo/Desktop/audio-fingerprint-identifying-python/libs/db.py", line 15, in get_song_by_filehash
    "filehash": filehash
  File "/Users/jesushedo/Desktop/audio-fingerprint-identifying-python/libs/db_sqlite.py", line 61, in findOne
    return self.executeOne(select['query'], select['values'])
  File "/Users/jesushedo/Desktop/audio-fingerprint-identifying-python/libs/db_sqlite.py", line 34, in executeOne
    self.cur.execute(query, values)
sqlite3.OperationalError: no such table: songs
sqlite - connection has been closed

**Comment by ZhymabekRoman** [comment]
Hello!I also had this problem. I solved it this way:
```
make clean reset
```

**Comment by hedo95** [comment]
Solved! you saved my day :)
