### ISSUE TITLE
make clean reset

### ISSUE THREAD

**Issue by picozone** [itspoma/audio-fingerprint-identifying-python#29]
Could you help me ?

Traceback (most recent call last):
  File "/home/prosper/Dev/audio-fingerprint-identifying-python/reset-database.py", line 2, in <module>
    from libs.db_sqlite import SqliteDatabase
  File "/home/prosper/Dev/audio-fingerprint-identifying-python/libs/db_sqlite.py", line 1, in <module>
    from db import Database
ImportError: cannot import name 'Database' from 'db' (unknown location)
make: *** [Makefile:10 : reset] Erreur 1

What's wrong please ?

**Comment by MeaningOfLights** [comment]
You're probably running on Windows, best to run this through WSL and use a virtual environment. I got this error and that's how I got around it.

**Comment by ujagrati** [comment]
i am running this on Linux with pYthon 2.7 still not working make clean reset command.
please help asap
