### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by vijender412** [itspoma/audio-fingerprint-identifying-python#5]
The problem occurs when we try to execute the collect fingerprint file
Traceback (most recent call last):
  File "C:/Users/BARRETT/Desktop/audio-fingerprint-identifying-python-master/collect-fingerprints-of-songs.py", line 24, in <module>
    audio = reader.parse_audio()
  File "C:\Users\BARRETT\Desktop\audio-fingerprint-identifying-python-master\libs\reader_file.py", line 34, in parse_audio
    audiofile = AudioSegment.from_file(self.filename)
  File "C:\Python27\lib\site-packages\pydub\audio_segment.py", line 505, in from_file
    p = subprocess.Popen(conversion_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by itspoma** [comment]
Hey @vijender412 ! It seems like audio file is not exist on directory that you've specified.

**Comment by vijender412** [comment]
Yes thanks got fixed. 😅😅
Too old to remember now but I got the issue fixed. It was mac using / instead of \ while specifying the path.
