### ISSUE TITLE
TypeError: numpy boolean subtract, the `-` operator, is deprecated

### ISSUE THREAD

**Issue by Naereen** [itspoma/audio-fingerprint-identifying-python#8]
```python
Traceback (most recent call last):
  File "collect-fingerprints-of-songs.py", line 53, in <module>
    channel_hashes = fingerprint.fingerprint(channel, Fs=audio['Fs'], plots=config['fingerprint.show_plots'])
  File "audio-fingerprint-identifying-python/libs/fingerprint.py", line 95, in fingerprint
    local_maxima = get_2D_peaks(arr2D, plot=plots, amp_min=amp_min)
  File "audio-fingerprint-identifying-python/libs/fingerprint.py", line 115, in get_2D_peaks
    detected_peaks = local_max - eroded_background
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logic al_xor function instead.
```
With most up-to date `numpy` on Python 2.

**Comment by Naereen** [comment]
https://github.com/itspoma/audio-fingerprint-identifying-python/blob/master/libs/fingerprint.py#L115
